---
title: Primer on the Rights Retention Strategy
author:
  - Stephen J Eglen^[University of Cambridge, sje30@cam.ac.uk, https://doi.org/10.5281/zenodo.4641752]
output:
  pdf_document:
     includes:
       in_header: "pandoc-header.tex"
date: 2021-03-27 v0.22 pre
urlcolor: blue
bibliography: <!-- \bibliography{/Users/kjhealy/Documents/bibs/socbib-pandoc.bib} This is a hack for Emacs users so that RefTeX knows where your bibfile is, and you can use RefTeX citation completion in your .md files. -->
---


# 


\onehalfspacing

## Abstract

The rights retention strategy (RRS) is a new tool to help academic
authors retain rights over their manuscripts. This will allow you to
freely share your author accepted manuscript at any time.  The RRS is
simple and elegant; authors need follow only two steps. (1) Add the
following text, e.g. to the cover page, or acknowledgements, to your
manuscript before submission to a journal: "A CC BY or equivalent
licence is applied to the AAM arising from this submission." (2) Once
your article is accepted for publication, you can deposit your version
of the manuscript in a public repository.  This strategy has been
developed by cOAlition-S, but can be used by all authors, irrespective
of funding.  Here I describe pros and cons of this approach, but
recommend its adoption by scholars as a way to retain ownership of
their own content.



**Abbreviations: ** 
AAM: Author Accepted Manuscript;
CC BY: Creative Commons Attribution Licence;
RRS: Rights Retention Strategy; 
VOR: Version Of Record.


**This is written by researchers, for researchers, very much
work-in-progress during 2021. Comments welcome.
See <https://github.com/sje30/rrs> for sources. **


# Introduction

Congratulations!  Your paper has just been accepted for publication in
a journal.  Your excitement may soon fade however when it turns to the
thorny issue of complying with open access policies.  Your funders may
readily pay the article processing charge (APC) if you have chosen a
fully open access journal.  Or you may have chosen a diamond OA venue
where there is no APC.  But what if you have chosen to publish
in a subscription journal with an option to publish open access
(sometimes called 'hybrid')?  If your funder is a member of cOAlition
S, they will not pay for the APC, and it is likely that your
institution won't either; how can you make your article open access
without recourse to funds for paying the APC?


One thing you might wish to do is to freely share the version of the
manuscript that the journal has been accepted, the so-called
"author-accepted manuscript".  This version is *your* manuscript,
taking on board comments during the review process (editors and
reviewers, who are typically your colleagues).  Many journals,
however, demand that you should not share your own AAM until an
embargo period (often 6--24 months) has passed.  These first few months
are often vital for the visibility of your papers.

![Typical life cycle of a manuscript.  Time goes from left-to-right in
this diagram.  Authors (bottom) send their first paper (V1) to the
editor (top) and receive reviews in return.  After two rounds of
revisions, the editor deems the paper acceptable ("OK").  When the
paper is accepted, the latest version (3) automatically becomes the
author-accepted manuscript (AAM) which can be freely shared.  Some
time later, the publisher updates V3 to produce the version of record
(VOR).](ms_changes-crop.pdf)


Once a journal has finished turning your manuscript into the final
article by suitable typesetting and reformatting, the 'version of
record' (VOR) is born (Figure 1). Hence your paper is usually exists
in two different formats: the AAM and the VOR.  Sharing AAMs provides
an equitable approach to open access for your research, as no APC is
required.  Furthermore, the AAM can be made freely available as soon
as the editor tells you your work will be accepted by the journal.
The VOR often takes weeks/months to appear, often behind a paywall,
after an editor has agreed that your paper has been accepted.


So, how can you legally share your AAM immediately upon publication?
There are several approaches to this [refs], of which the latest is
the "Rights Retention Strategy" (RRS), developed by cOAlition S.  In
this primer, I describe what the RRS is and its pros and cons.  I have
written this because current advice seems conditioned on the principle
that your work has been supported by a funder that is part of
cOAlition S.  However the RRS statement is a tool that ALL authors can
use, irrespective of funding.


## What is the RRS?

The RRS is a means for authors to retain sufficient rights in their
own work to be able to use their own work as they choose.  As shown in
the abstract of this primer, the RRS is the following sentence that
you add prominently to the cover page or acknowledgements before
submitting it to a journal:

    A CC BY or equivalent licence is applied to the AAM arising from this submission.

(Authors funded by the Wellcome Trust should use a [two sentence
version](https:/wellcome.org/grant-funding/guidance/open-access-guidance/complying-with-our-open-access-policy) that ensures their grant number is also listed appropriately.
This magic sentence alerts the editor at the start of the submission
process of your intention to share your AAM under a CC BY licence (a
permissive copyright licence).  Using it upon submission gives you the
right to freely share the AAM that will result from your initial
submission.
The journal can either accept your manuscript (with its magic text)
for consideration for publication, or decline it.  No publishers have
so far indicated that they will routinely decline manuscripts that
include the text.

It might seem pragmatic to routinely adopt this text in our
manuscripts.  Even if you plan to send the manuscript to a publisher that
does not ask you to sign away your rights, it sets a good example to
others in the community.  Although the RRS is fairly new, examples of
the RRS are already in the literature.  Here are three found by Ross
Mounce: [1](https://twitter.com/rmounce/status/1368930651844579335),
[2](https://twitter.com/rmounce/status/1368932955465383936),
[3](https://twitter.com/rmounce/status/1369775832680587270).


## What are the advantages for an author?

If the RRS statement is adopted, it offers a way to publish in hybrid
journals and make the work immediately open access without paying an
APC.  It signals to the publishing community that authors are keen to
keep sufficient intellectual rights to use their own work.  Much is
made by publishers of the "hallowed status" of the VOR. e.g. it is
referred to as ["the foundation of the scientific
record"](https://ioppublishing.org/signatories_publish_statement_on_rights_retention_strategy/).  The RRS provides a way by which the author can make their manuscript
open access, and the publisher can then later publish a
"bells-and-whistles" version of your work, with their own branding and
formatting.







## What are the disadvantages?

It is simply too early to tell if this RRS will have any impact in
scholarly communication.  The journal *Science* is currently trialling
a [pilot
program](https://www.eurekalert.org/pub_releases/2021-01/aaft-foa011421.php)
where it will accept manuscripts using the RRS from authors if (and
only if) they are funded by plan-S funders (M Phelan, personal
communication).  The only subscription-based publishers that seem to
endorse the RRS are the *Royal Society* and the *Microbiology society*
(<https://www.coalition-s.org/rights-retention-strategy>).

Several concerns have been raised already:

1. Your paper might be desk-rejected, i.e. rejected by  editorial team
   rather than going out for peer review.

2. You might have your paper accepted in principle, only to find that
the publisher demands some embargo on publication of the AAM as a
condition of publishing the paper.  However, since that request for
embargo comes after you have claimed a CC BY licence, your CC BY
licence takes legal precedence over any restriction the publisher
tries to place on your AAM.  *You are free to do with the AAM as
you please.*

3. You might be asked to pay an APC up-front before the paper is sent
   out to review.
   
4. The editorial team might redirect your article from one journal to
   a different journal that requires an APC.


It can be assumed that problems 3 and 4 have already occurred given
the publication of guidance from Wellcome in March 2021 <https://wellcome.org/press-release/publishing-hybrid-open-access-journals>.

Many traditional publishers have signed a letter [objecting to the
RRS](https://ioppublishing.org/signatories_publish_statement_on_rights_retention_strategy/).
Their fundamental objection is  that they are the only
trusted guardians of the publishing record, and that they need to
protect their business.

So although you should be able to use the RRS to freely share your
AAM, you may meet resistance from publishers, and journals may refuse
to accept your work for review.  If this happens, I am truly sorry, but your
only recourse would be to inform the community and hope that
visibility of their actions will cause publishers to remove their
objections.  Those funded by cOAlition S funders should also inform
their funders who are monitoring publishers' reactions carefully.

<!-- todo -->
<!-- **I would also suggest involving COPE [MATT?].** -->

## Related approaches

This idea of preserving author rights during publication is not new;
several other routes are available to particular communities, starting
with US universities (<https://bit.ly/goodoa>). Legislation has also
been used, e.g. in France and Belgium, to allow researchers to share their
own work, although typically only after an embargo.  What does seem to
be new with the RRS is that the publisher is alerted at the time of
initial submission about the intention to use the RRS.


## Will it help authors?

Scholarly communications seems like an epic game of chess played out
over decades.  Just as funders think there is some solution,
publishers respond with moves that were unintended.  For example, the
rise of hybrid publications, and escalating APCs came in response to
the [Finch report from the UK
government](https://www.repository.cam.ac.uk/handle/1810/269913).  I
doubt the RRS is the silver bullet, but if nothing else it is a useful
tool to raise awareness of scholarly communications and in particular
the ability of authors to retain rights to use their own works as they
choose.  Even if you are a well-funded researcher that can afford high
APCs, the current system excludes many researchers, particularly from
regions such as [Latin
America](https://septentrio.uit.no/index.php/SCS/article/view/4964)
that cannot afford high APCs.


It may be that the RRS is a tool that may disappear after a few years,
if publishers accept that authors hold the rights to their AAM.  In
this sense, the RRS would have been a success, even if no longer
required, as it brought about the necessary change.  However,
experience has shown us that publishers are capable of responding to
strong moves with equally strong moves, and what "unintended
consequences" there may be of adopting the RRS.  However, given how
messed up scholarly communications appears both inside and outside of
the academic bubble, I doubt it will make matters worse for us as
academics.

In a nutshell, if traditional publishers see the RRS as a threat to
their continued existence, then this at least promotes discussion.  I
would rather see more equitable OA practices, such as overlay and
[diamond OA
journals](https://www.coalition-s.org/diamond-unearthed-shining-light-on-community-driven-open-access-publishing/).
I would urge every academic to start using the RRS in their
manuscripts, and would encourage our academic institutions to endorse
this strategy.



## Further reading

The [cOAlition S
website](https://www.coalition-s.org/rights-retention-strategy/) has
further material describing the RRS in detail.  Lisa Hinchliffe has
written a [blog
post](https://scholarlykitchen.sspnet.org/2021/02/17/rights-retention-strategy)
on this topic.


## Acknowledgements

I thank the following for comments and feedback on this article:
Rupert Gatti, Ross Mounce, Benjamin Reese, Johan Rooryck, Sally
Rumsey.  Thanks to Lisa Hinchliffe for comments online.  A CC BY or
equivalent licence is applied to the AAM arising from this submission.








<!-- \clearpage -->
<!-- # Notes. -->

<!-- ## relevant links: -->

<!-- # Version history -->

<!-- ## 0.1 -->


<!-- Working towards an initial public release for feedback. -->

<!--  <\!--  -->
<!--  ~/papers/2013_enc/forweb/maps1.md -->
<!--  -\-> -->

<!-- \clearpage -->

<!-- # Cut text -->


<!-- However, this seems like an outdated idea -- research is not -->
<!-- a single PDF.  By contrast, papers can evolve over time (and DOIs can -->
<!-- now be suitably versioned): -->


<!-- "However, VOR did not appear on the eighth day of Creation; it really -->
<!-- is the spin-off of a particular technology, print." Jean-Claude -->
<!-- Guédon, in response to post <https://oaspa.org/open-post-the-rise-of-immediate-green-oa-undermines-progress/> -->


<!-- Cut this, as it is a nice point, but perhaps peripheral. -->
<!-- In other areas, e.g. computing, we have embraced the notion of version -->
<!-- control, and versioning, to allow us to refer to software at different -->
<!-- points in time, rather than a single thing.  Why restrict papers to a -->
<!-- single published version?  As long as researchers are explicit about -->
<!-- which version of a paper they are citing, there is no problem (ideally -->
<!-- if the object being cited is freely available).  This idea is -->
<!-- gradually being adopted in scholarly communications, e.g. moving away -->
<!-- from "version of record" to "record of versions" (a term coined by -->
<!-- Bianca Kramer), which seems a much richer idea. -->


<!-- <https://oaspa.org/open-post-the-rise-of-immediate-green-oa-undermines-progress/> -->



<!--  LocalWords:  cOAlition AAM RRS funder OA VOR funders
 -->
