---
title: A researcher's guide to using the rights retention strategy (version 0.3)
author: Stephen J Eglen
date: today
date-format: iso
bibliography: ukrn.bib
geometry:
  margin=25mm
format:
  pdf:
    pdf-engine: pdflatex
    papersize: A4
    keep-tex: true
    documentclass: article
    include-in-header: header.tex
    include-before-body: before.tex
    fontfamily: mathpazo
---

# What is rights retention?

The internet has transformed the way that many researchers work.  We
can now rapidly share both digital research artefacts and computer
programmes for processing the artefacts.  This freedom to share our
digital artefacts is exciting and is rapidly transforming many
academic disciplines.  A range of [copyright
licences](https://libguides.cam.ac.uk/copyright/researchers) now exist
to allow researchers to both retain rights on their work whilst being
able to also share their work.  The use of standard licences,
particularly the creative commons (CC) family, makes our jobs as
academics relatively painless and robust.  This ability to share our
scholarly products is a key academic principle that hopefully most
researchers will find natural and uncontroversial.  Furthermore, most
UK grant agencies require data management plans as a condition of
funding to maximise the potential reuse of the research that they
fund.

In parallel to this growth of open research, UK research councils and
major funding bodies now require that our published research articles
must freely available without embargo under particular copyright
licences (such as CC-BY).  Journal publishers have responded to these
requirements in various ways, e.g. by offering 'gold open access'
routes, that often require payment of substantial article processing
charges (APCs).

Funders also permit 'green open access' as a route to compliance with
their rules.  This is where the author makes their version of the
manuscript (the peer-reviewed author accepted manuscript, AAM) freely
available via an institutional repository or similar archive.  Many
publishers have previously allowed some form of self-archiving, but
usually with constraints, e.g. imposition of an embargo period
(between 6-24 months).  These constraints contradict funders'
requirements that prohibit any embargo period.

In response to these restrictive embargo periods, and to encourage
open research, academic institutions and researchers have developed
their own policies to permit sharing of their work.  Perhaps the most
well-known example of these is the policy led by
[Harvard](https://osc.hul.harvard.edu/policies/) faculty in 2008.
Within the UK, proposals for a UK Scholarly Communications Licence
[UK-SCL](https://ukscl.ac.uk/) have been created.  Internationally,
the ``[rights retention strategy](https://www.coalition-s.org/rights-retention-strategy/)''
been developed by a group of international funders, cOAlition S, to
allow researchers to retain rights on their scholarly writing and thus
meet the requirements of their funders.

This guide describes how authors can retain rights on their
manuscripts using the rights retention strategy.


# Why should authors retain their rights?

Authors should retain their rights so that it they, not a third
party, retain control over uses of their own manuscripts. This
includes when and to whom their manuscript can be disseminated, and
means that researchers treat manuscripts in a similar fashion to other
digital artefacts that they wish to share.  Another important reason
why researchers might wish to retain their rights is to comply
with funders' requirements.  Ignoring funders' requirements could affect
a researcher's chance of future funding.  This might be seen by some
researchers as simple rule-following with little benefit to
themselves.  However, work that is available open-access tends
to be more highly cited than work that is only available behind a
paywall [@Langham-Putrow2021-qf].  Open-access licences on work allows
for rapid reuse by everyone in the community, including the
researchers who originally created the material.  This includes, but is
not limited to to books, talks, wikipedia and social media, for
teaching and research.

In many professional disciplines, the creator of the work naturally
maintains rights to their work.  Many journal publishers state that
they require exclusive rights to publish the work.  This is simply not
true [@Suber2022-dm].

# How to retain rights to your manuscripts

The process of retaining rights on your manuscripts is
simple.  Before submitting your work to a journal, add the following
phrase to your manuscript e.g. in the Acknowledgements
section:

    For the purpose of open access, the author has applied a Creative
	Commons Attribution (CC BY) licence to any Author Accepted
	Manuscript version arising from this submission.

It is also a good idea to tell the editor, in your cover letter, that
you wish to retain rights to any author-accepted manuscript resulting
from your submission.

That's it.  If your paper is accepted by the editor after peer-review,
your author accepted manuscript can then be deposited in a suitable
open repository under a CC-BY licence without embargo.  You are then
free to also share the manuscript however you choose.  (Some
disciplines may prefer other forms of creative commons licence that
prevent e.g. commercial use; many funders allow this but it may
require you to apply for an exemption.)

This approach is endorsed and recommended by major research funders,
including the Wellcome Trust and all of the UK Research Councils.

## What if things go wrong?

In the majority of cases, researchers to date have faced no issues
when using the rights retention strategy to make their manuscripts
freely available without embargo.  However, there are several issues
to be aware of:

1. A journal editor may decline reviewing ("desk reject") your
   manuscript because it uses rights retention language.  Whilst
   unfortunate, each publisher is free to decline to review articles
   for many reasons.  However, although many traditional publishers
   have voiced their concerns about rights retention
   <https://ioppublishing.org/signatories_publish_statement_on_rights_retention_strategy/>,
   those same publishers are allowing authors to exert their natural
   rights
   <https://github.com/rossmounce/rrs-language-including-outputs>.

2. One of the largest publishers, Springer Nature, noted in April 2021
   that in some cases they will effectively ignore rights retention
   language in manuscripts
   <https://www.springernature.com/gp/advancing-discovery/blog/blogposts/continuing-the-open-access-transition/19045440>
   and require a transfer of copyright.  This will create a conflict
   once the manuscript has been editorially accepted.  Ignoring
   researcher rights on their work is highly unethical, and puts
   researchers in a very difficult position.  To avoid this stalemate,
   a researcher could seek confirmation from the editor that they can
   retain their rights before submitting their manuscript.  A simpler
   approach would be to avoid that publisher.
   
3. If you publish your work in a subscription journal, as long as you
   make your AAM freely available without embargo, you do not need to
   pay the journal an APC.  (The journal may still demand other
   charges, such as for colour figures in-print.)  However, if you
   publish your work in an open-access journal, you may still need to
   pay an APC to have your work published.  Often these costs are
   covered by institutional arrangements with the publisher.

The route to open access can occasionally be more complicated than it
need be.  If in doubt, researchers may seek local advice e.g. from
library staff, when choosing which journal to submit their work to,
and funding sources for any charges. The journal checker tool
<https://journalcheckertool.org/> provides information about journal
compliance with funders' OA policies, and provides simple options for
you to follow.


## Institutional support for rights retention

Researchers can and should use the rights retention strategy by
themselves to ensure they retain some control of their own
manuscripts, and to assist them with complying with funders’
requirements for open access.  To support their researchers, several
UK institutions have already adopted rights retention policies that
apply to their employees.  These policies typically give the
institution a non-exclusive right to archive author accepted
manuscripts and make them available via their repository.  The
researcher gains an extra layer of institutional support in the
(hopefully rare) case that a publisher raises a concern with rights
retention language in the manuscript  (i.e. an author wishing to
retain rights that are rightfully theirs).  Some universities have
publicly stated their support for their researchers should any of
their authors be challenged by a publisher.  A list of current
UK institutional policies is available at:
<https://github.com/sje30/rrs/blob/main/ukinstitutions.csv> ; this
list is expected to grow considerably during 2023 and 2024.  However,
even with an institutional policy supporting the researcher, it is
pragmatic to still include the rights retention statement in your
manuscript.

# Closing comments

Adopting the rights retention language in manuscripts is a clear and
simple step that all authors can take to maintain rights over their
work.  It has been adopted successfully in the last few years by many
authors.  Despite several publishers raising concerns with it in 2021,
there has yet to be any major objection raised when researchers assert
their natural rights.  To further support researchers, UK institutions
are adopting policies to allow their employees to share their author
accepted manuscripts without embargo.

<!-- (setq reftex-default-bibliography '("ukrn.bib")) -->

<!-- 

(quarto-mode-bibliography-entry)
(setq reftex-cite-format "@%l")
-->

# References

::: {#refs}
:::

# Changes

## version 0.3

In this version I thank feedback from the several reviewers.  I have
implemented almost all of their suggestions.  Of note:

1. The title has been changed.
2. A new opening paragraph has been added to highlight the benefits of
   open research, which in turn relies on licencing.
3. I have tightened the section 'What if things go wrong'?

In addition to these reviewer suggestions, I've added a brief closing comment.
   
and now spell-checked!
